#!/bin/bash

### This script is called after the user uninstalls the application.

[ "${wizard_data_action:-}" == "delete" ] && {
  rm -rf "${TRIM_PKGVAR}"
  while read -r path; do rm -rf "${path}"; done <<<"$(echo "${TRIM_DATA_SHARE_PATHS}" | tr ':' '\n')"
}

exit 0
